apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zed-progress
  description: # Zed Progress 4GL Extension
  annotations:
    backstage.io/techdocs-ref: dir:.

  tags:
    - tool
spec:
  type: tool
  lifecycle: production
  owner: team-default
